version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: enviedici
      POSTGRES_USER: enviedici
      POSTGRES_PASSWORD: enviedici
    ports:
      - "5432:5432"
    restart: unless-stopped

  django-app:
    build: ./django_backend
    container_name: django_app
    entrypoint: ["./entrypoint.sh"]
    volumes:
      - ./django_backend:/app
      - ./volumes/static:/app/static
      - ./volumes/media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./django_backend/.env
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./angular-app
    container_name: angular_frontend
    ports:
      - "4200:80"
    restart: unless-stopped
    depends_on:
      - django-app

volumes:
  pgdata:
