version: "3.8"

services:
  angular:
    build:
      context: ./angular-app
    container_name: angular-frontend
    ports:
      - "4200:80"
    networks:
      - enviedici-net

  django:
    build:
      context: ./django_backend
    container_name: django-backend
    ports:
      - "8000:8000"
    env_file:
      - ./django_backend/.env
    networks:
      - enviedici-net

networks:
  enviedici-net:
    driver: bridge
