version: "3.8"

services:
  angular:
    build:
      context: ./angular-app
    container_name: angular
    ports:
      - "4200:80"
    networks:
      - enviedici-net

  django:
    build:
      context: ./django_backend
    container_name: django
    ports:
      - "8000:8000"
    env_file:
      - ./django_backend/.env
    networks:
      - enviedici-net

  postgres:
    build:
      context: ./postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: enviedici
      POSTGRES_USER: enviedici
      POSTGRES_PASSWORD: enviedici
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - enviedici-net

networks:
  enviedici-net:
    driver: bridge

volumes:
  postgres-data:
