apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
        - name: django-backend
          image: enviedici-django-app:latest
          imagePullPolicy: Never
          command: ["/app/entrypoint.sh"]
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              value: "django-insecure-1234567890"
            - name: DEBUG
              value: "True"
            - name: ALLOWED_HOSTS
              value: "localhost,127.0.0.1"
            - name: POSTGRES_DB
              value: "enviedici"
            - name: POSTGRES_USER
              value: "enviedici"
            - name: POSTGRES_PASSWORD
              value: "enviedici"
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
          volumeMounts:
            - name: static-volume
              mountPath: /app/static
            - name: media-volume
              mountPath: /app/media
      volumes:
        - name: static-volume
          emptyDir: {}
        - name: media-volume
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
